website/myapp/urls.py
#myappの方

from django.urls import path
from . import views
 
app_name='myapp'
 
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^like/$', views.like, name='like'),
    url(r'^dislike/$', views.dislike, name='dislike'),
    url(r'^birthday/$', views.birthday, name='birthday'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

website/myapp/models.py
from django.db import models

# Create your models here.

website/myapp/views.py
from django.shortcuts import render


def index(request):
    return render(request,'index.html')

# Create your views here.
from django.shortcuts import render # render関数
 
def index(request): # index関数
    return render(request,'index.html') # index.htmlを返す
 
def welcome(request): # welcome関数
	return render(request, 'welcome.html') # welcome.htmlを返す
 
def like(request): # like関数
    return render(request,'like.html') # like.htmlを返す
 
def dislike(request): # dislike関数
    return render(request,'dislike.html') # dislike.htmlを返す
 
def birthday(request): # birthday関数
    return render(request,'birthday.html') # birthday.htmlを返す

website/myapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static "css/style.css" %}"/>
 
        <title>我が家の愛犬パオの日記</title>
    </head>
 
    <body>
 
        <h1>我が家のの愛犬パオの日記</h1>
 
        <img src="{% static "images/inu.png" %}" alt="表示できません">
 
        <h2>我が家の可愛い愛犬ポチを紹介するホームページです。</h2>
 
        <p><a href="{% url 'myapp:welcome' %}">可愛いわんちゃんがうちに来てくれました</a></p>
        <p><a href="{% url 'myapp:like' %}">ポチの好きな食べ物</a></p>
        <p><a href="{% url 'myapp:dislike' %}">ポチの嫌いな食べ物</a></p>
        <p><a href="{% url 'myapp:birthday' %}">ポチが１１才になりました</a></p>
 
    </body>
 
</html>